---
  - name: Install Python PyMySQL driver (for Ansible MySQL modules)
    apt:
      name: python3-pymysql
      state: present
      update_cache: true

  - name: Install MariaDB server
    apt:
      name: mariadb-server
      state: present
      update_cache: true

  - name: Ensure MariaDB is started and enabled
    service:
      name: mariadb
      state: started
      enabled: true

  - name: Secure installation (root user with no password for dev)
    mysql_user:
      name: root
      host: localhost
      password: ""
      login_unix_socket: /var/run/mysqld/mysqld.sock
      check_implicit_admin: true

  - name: Enable innodb_file_per_table globally
    mysql_variables:
      variable: innodb_file_per_table
      value: '1'
      config_file: /etc/mysql/my.cnf
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Create Gogs database
    mysql_db:
      name: gogs
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
      encoding: utf8mb4
      collation: utf8mb4_general_ci

  - name: Create Gogs user
    mysql_user:
      name: gogs
      password: gogs_password
      priv: "gogs.*:ALL"
      host: "%"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Allow remote access to MariaDB (bind to all interfaces)
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address'
      line: 'bind-address = 0.0.0.0'
      state: present
      backup: yes

  - name: Restart MariaDB after config change
    service:
      name: mariadb
      state: restarted

