---
  - name: Create git user
    user:
      name: "{{ gogs_username }}"
      shell: /bin/bash
      home: "/home/{{ gogs_username }}"
      create_home: yes

  - name: Download Gogs binary archive
    get_url:
      url: "{{ gogs_download_link }}"
      dest: /tmp/gogs.tar.gz
      mode: '0644'

  - name: Ensure /home/git directory exists
    file:
      path: "/home/{{ gogs_username }}"
      state: directory
      owner: "{{ gogs_username }}"
      group: "{{ gogs_username }}"
      mode: '0755'

  - name: Extract Gogs archive to /home/git
    unarchive:
      src: /tmp/gogs.tar.gz
      dest: "/home/{{ gogs_username }}"
      remote_src: yes

  - name: Set ownership of /home/git recursively
    file:
      path: "/home/{{ gogs_username }}"
      owner: "{{ gogs_username }}"
      group: "{{ gogs_username }}"
      recurse: yes

  - name: Copy gogs.service to systemd
    template:
      src: gogs_service.j2
      dest: /etc/systemd/system/gogs.service
      mode: '0644'

  - name: Create gogs/custom/conf directory
    file:
      path: "/home/{{ gogs_username }}/gogs/custom/conf"
      state: directory
      owner: "{{ gogs_username }}"
      group: "{{ gogs_username }}"
      mode: '0755'

  - name: Create custom app.ini file
    template:
      src: gogs_config.j2
      dest: "/home/{{ gogs_username }}/gogs/custom/conf/app.ini"

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes

  - name: Enable and restart gogs service
    systemd:
      name: gogs
      state: restarted
      enabled: yes
